### ISSUE TITLE
The beam rifle has broken zoom

### ISSUE THREAD

**Issue by Shad0wShayd3** [Alex-231/Halo-3-HUD-for-Halo-Online#2]
Zooming with a beam rifle is broken as shit, as in, zooming with a Beam Rifle crashes the game.

I tested by changing the Beam Rifle to use the Sniper's chdt, and gave the sniper the Beam Rifle chdt, and it breaks when the chdts are swapped, so it's a broken within the beam rifle's chdt, probaby a texture or something.

**Comment by Alex-231** [comment]
http://i.icap.me/3514470175345eb3.png

Could not replicate.

**Comment by Alex-231** [comment]
Reproduced on a different device. 
Notable differences:
- High DPI
- Intel Graphics
- Low Graphics Settings

**Comment by Alex-231** [comment]
This bug has been fixed, but has caused a new issue, https://github.com/Alex-231/Halo-3-HUD-for-Halo-Online/issues/3
